name: Build System CI

on:
  pull_request:
    branches:
    - master

jobs:
  spotless:
    name: Spotless checks
    runs-on: ubuntu-latest
    env:
      BUILD_SYSTEM_VERSION: '2.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Execute Spotless checks
        run: |
          echo "apply from: '$(pwd)/${BUILD_SYSTEM_VERSION}/vividus-test-project.gradle'" >> build.gradle
          # The presence of .gitignore file is required by build system
          touch .gitignore
          ./${BUILD_SYSTEM_VERSION}/gradlew spotlessCheck
